import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/nav/navbar";
import LoginLogoutButton from "./ui/nav/login-logout-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen overflow-hidden">
      <body
        className={`antialiased h-screen flex flex-col m-0 p-0 overflow-hidden`}
      >
        <Navbar loginLogoutBtn={<LoginLogoutButton/>}/>
        <div className="flex-1 overflow-y-auto">
            <main className="flex flex-col min-h-full w-full justify-center items-center p-4">
                {children}
            </main>
        </div>
        <footer className="h-12 shrink-0 flex items-center justify-center text-sm">
          <p className="mb-4">Copyright 2026</p>
        </footer>
      </body>
    </html>
  );
}
